name: "Telegram Message Notify"
description: "Sending a Telegram message"
author: "Jairo Julià Bravo"
inputs:
  to:
    description: "telegram user"
    required: true
  token:
    description: "telegram token"
    required: true
  message:
    description: "telegram message"
    required: false
  message_file:
    description: "overwrite the default message template with the contents of the specified file"
    required: false
  photo:
    description: "send the photo message."
    required: false
  document:
    description: "send the document message."
    required: false
  sticker:
    description: "send the sticker message."
    required: false
  audio:
    description: "send the audio message."
    required: false
  voice:
    description: "send the voice message."
    required: false
  location:
    description: "send the location message."
    required: false
  venue:
    description: "send the venue message."
    required: false
  video:
    description: "send the video message."
    required: false
  debug:
    description: "enable debug mode."
    required: false
  format:
    description: "message format: markdown or html"
    required: false
  disable_web_page_preview:
    description: "disables link previews for links in this message"
    required: false
runs:
   using: "node12"
   main: "../../dist/index.js"  #se ponde dist por que vercel mimifica

branding:
  icon: "message-square"
  color: "blue"
