name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: El ${{ github.event_name }} a inciado el primer Step.

    - name: send message useing with
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          El ${{ github.event_name }} a inciado el segundo Step.
          REF: ${{ github.ref }}
          COMMIT: ${{ github.sha }}
          COMMIT REF: {{ commit.ref }}
          COMMIT SHA: {{ commit.sha }}
          COMMIT MESSAGE: ${{ github.event.head_commit.message }}

    - name: send default message
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}

    - name: send photo message
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Ahora te mandaré una foto
        photo: './tests/github.png'
        document: './tests/gophercolor.png'

    - name: send video message
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Ahora te mandaré una video
        video: './tests/video.mp4'

    - name: send audio message
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Ahora te mandaré una audio
        video: './tests/audio.mp3'    

    - name: send location message
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        location: '38.781779552388905, -0.4444032729369581'

    - name: send custom message
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          El ${{ github.event_name }} a inciado el último Step.
          echo This event is a pull request that had an assignee removed.

    - name: send message file
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message_file: tests/message.txt

    # - name: send message using socks5 proxy URL
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ secrets.TELEGRAM_TO }}
    #     token: ${{ secrets.TELEGRAM_TOKEN }}
    #     socks5: "http://222.124.154.19:23500"
    #     message: Send message from socks5 proxy URL.

    # - name: try multiple message
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ secrets.TELEGRAM_TO }}
    #     token: ${{ secrets.TELEGRAM_TOKEN }}
    #     format: html
    #     message: |
    #       ⚡️ <a href="https://github.com/aszenz/repo/commit/${{ github.event.push.after }}">Commits</a> pushed to master by <em>${{ github.event.push.pusher.name }}</em> ⚡️
    #       ${{ github.actor }}:${{ github.event.head_commit.message }}

    - name: link preview
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Mostrar preview del enlace https://google.com.tw

    - name: disable link preview
      uses: ./
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_web_page_preview: true
        message: |
          Deshabilitar preview del enlace https://google.com.tw
